import '../models/cache_category.dart';
import '../models/cache_target.dart';
import '../models/profile.dart';
import '../models/risk.dart';
import '../global/global_cache_paths.dart';
import '../xcode/xcode_cache_paths.dart';

class TargetRegistry {
  static final List<CacheTarget> all = <CacheTarget>[
    // SAFE
    CacheTarget(
      id: 'project.build',
      category: CacheCategory.project,
      kind: CacheTargetKind.directory,
      minProfile: Profile.safe,
      risk: Risk.low,
      rationale: 'Flutter build output. Safe to delete; will be regenerated.',
      projectRelativePath: 'build',
    ),
    CacheTarget(
      id: 'project.dart_tool',
      category: CacheCategory.project,
      kind: CacheTargetKind.directory,
      minProfile: Profile.safe,
      risk: Risk.low,
      rationale: 'Dart tool cache. Safe to delete; will be regenerated.',
      projectRelativePath: '.dart_tool',
    ),
    CacheTarget(
      id: 'project.flutter_plugins',
      category: CacheCategory.project,
      kind: CacheTargetKind.file,
      minProfile: Profile.safe,
      risk: Risk.low,
      rationale: 'Generated plugin registrant file; regenerated by Flutter.',
      projectRelativePath: '.flutter-plugins',
    ),
    CacheTarget(
      id: 'project.flutter_plugins_deps',
      category: CacheCategory.project,
      kind: CacheTargetKind.file,
      minProfile: Profile.safe,
      risk: Risk.low,
      rationale: 'Generated plugin dependencies file; regenerated by Flutter.',
      projectRelativePath: '.flutter-plugins-dependencies',
    ),

    // MEDIUM
    CacheTarget(
      id: 'project.idea',
      category: CacheCategory.project,
      kind: CacheTargetKind.directory,
      minProfile: Profile.medium,
      risk: Risk.medium,
      rationale: 'IDE config/cache. Deleting may reset IDE settings.',
      projectRelativePath: '.idea',
    ),
    CacheTarget(
      id: 'project.android_gradle',
      category: CacheCategory.project,
      kind: CacheTargetKind.directory,
      minProfile: Profile.medium,
      risk: Risk.medium,
      rationale: 'Android Gradle project cache. Next build may take longer.',
      projectRelativePath: 'android/.gradle',
    ),
    CacheTarget(
      id: 'project.ios_pods',
      category: CacheCategory.project,
      kind: CacheTargetKind.directory,
      minProfile: Profile.medium,
      risk: Risk.medium,
      rationale: 'CocoaPods dependencies. Next iOS build may re-install pods.',
      projectRelativePath: 'ios/Pods',
    ),
    CacheTarget(
      id: 'project.ios_symlinks',
      category: CacheCategory.project,
      kind: CacheTargetKind.directory,
      minProfile: Profile.medium,
      risk: Risk.medium,
      rationale: 'Flutter iOS symlinks. Next iOS build may re-generate.',
      projectRelativePath: 'ios/.symlinks',
    ),

    // AGGRESSIVE (Global)
    CacheTarget(
      id: xcodeDerivedDataTargetId,
      category: CacheCategory.xcode,
      kind: CacheTargetKind.directory,
      minProfile: Profile.aggressive,
      risk: Risk.high,
      rationale:
          'Xcode DerivedData artifacts. Deleting increases iOS/macOS rebuild time.',
    ),
    CacheTarget(
      id: globalPubCacheTargetId,
      category: CacheCategory.global,
      kind: CacheTargetKind.directory,
      minProfile: Profile.aggressive,
      risk: Risk.high,
      rationale: 'Pub global cache. Deleting triggers package re-downloads.',
    ),
    CacheTarget(
      id: globalGradleUserHomeTargetId,
      category: CacheCategory.global,
      kind: CacheTargetKind.directory,
      minProfile: Profile.aggressive,
      risk: Risk.high,
      rationale:
          'Gradle user home cache. Deleting increases Android build time.',
    ),
    CacheTarget(
      id: globalCocoaPodsCacheTargetId,
      category: CacheCategory.global,
      kind: CacheTargetKind.directory,
      minProfile: Profile.aggressive,
      risk: Risk.high,
      rationale: 'CocoaPods cache. Deleting triggers pod re-download.',
    ),
    CacheTarget(
      id: globalCocoaPodsHomeTargetId,
      category: CacheCategory.global,
      kind: CacheTargetKind.directory,
      minProfile: Profile.aggressive,
      risk: Risk.high,
      rationale: 'CocoaPods home. Deleting triggers pod index/cache refresh.',
    ),
  ];

  static Iterable<CacheTarget> projectTargetsFor(Profile profile) sync* {
    for (final t in all) {
      if (t.category != CacheCategory.project) continue;
      if (!t.isIncludedIn(profile)) continue;
      yield t;
    }
  }

  static Iterable<CacheTarget> globalTargetsFor(Profile profile) sync* {
    for (final t in all) {
      if (t.category != CacheCategory.global) continue;
      if (!t.isIncludedIn(profile)) continue;
      yield t;
    }
  }

  static Iterable<CacheTarget> xcodeTargetsFor(Profile profile) sync* {
    for (final t in all) {
      if (t.category != CacheCategory.xcode) continue;
      if (!t.isIncludedIn(profile)) continue;
      yield t;
    }
  }

  static CacheTarget? byId(String id) {
    for (final t in all) {
      if (t.id == id) return t;
    }
    return null;
  }
}
